name: irc-bouncer
services:
  znc:
    container_name: znc
    image: znc:1.10.1
    ports:
      - 2020:2020
    volumes:
      - znc-cfg:/znc-data
    restart: unless-stopped

volumes:
  znc-cfg:
    name: znc-cfg
